import React, { useState, useEffect } from 'react';
import { SpinnerIcon } from './icons/SpinnerIcon'; // Assuming you have a SpinnerIcon for loading effect

interface InitialDisclaimerSplashProps {
  onAccept: () => void;
}

const InitialDisclaimerSplash: React.FC<InitialDisclaimerSplashProps> = ({ onAccept }) => {
  const [agreements, setAgreements] = useState({
    legalAdvice: false,
    noGuarantees: false,
    liability: false,
    testimonials: false,
    userResponsibility: false,
  });
  const [allAgreed, setAllAgreed] = useState(false);
  const [isAnimatingOut, setIsAnimatingOut] = useState(false);

  useEffect(() => {
    const allChecked = Object.values(agreements).every(Boolean);
    setAllAgreed(allChecked);
  }, [agreements]);

  const handleCheckboxChange = (key: keyof typeof agreements) => {
    setAgreements(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const handleContinue = () => {
    if (allAgreed) {
      setIsAnimatingOut(true);
      setTimeout(onAccept, 500); // Match fade-out duration
    }
  };

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        backgroundColor: 'var(--color-bg)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 100,
        padding: '1.5rem',
      }}
      className={isAnimatingOut ? 'animate-fade-out' : 'animate-fade-in'}
    >
      <div
        className="smoked-glass-pane animate-pop-in"
        style={{
          width: '100%',
          maxWidth: '56rem',
          height: '90vh',
          maxHeight: '800px',
          padding: '2rem',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          overflowY: 'auto',
          textAlign: 'left',
        }}
      >
        <div>
          <h1
            style={{
              fontFamily: 'var(--font-serif)',
              fontSize: 'clamp(2rem, 5vw, 3rem)',
              textAlign: 'center',
              marginBottom: '1.5rem',
              color: 'var(--color-primary)',
            }}
          >
            Important Legal Disclaimer & Terms of Use
          </h1>

          <div
            style={{
              maxHeight: 'calc(90vh - 250px)', // Adjust based on header/footer height
              overflowY: 'auto',
              paddingRight: '1rem',
              marginBottom: '1.5rem',
            }}
          >
            <h2 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.5rem', marginBottom: '0.75rem' }}>
              1. AI Legal Information, Not Advice
            </h2>
            <p style={{ marginBottom: '1rem' }}>
              A²Z AssistanZ is an AI-powered tool designed to provide general legal information, assist in document generation, and facilitate communication. It is{' '}
              <strong style={{ color: 'var(--color-primary)' }}>NOT a substitute for professional legal advice</strong> from a qualified attorney. The information and documents provided by this application are for informational purposes only and do{' '}
              <strong style={{ color: 'var(--color-primary)' }}>NOT constitute legal advice, legal services, or an attorney-client relationship</strong>. Always consult with a licensed legal professional for advice specific to your situation.
            </p>

            <h2 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.5rem', marginTop: '1.5rem', marginBottom: '0.75rem' }}>
              2. No Guarantees, No Warranties
            </h2>
            <p style={{ marginBottom: '1rem' }}>
              The accuracy, completeness, or reliability of any information or documents generated by A²Z AssistanZ is{' '}
              <strong style={{ color: 'var(--color-destructive)' }}>not guaranteed</strong>. Your use of this application and reliance on any information or output from it is solely at your own risk. We disclaim all warranties, express or implied, including but not limited to, implied warranties of merchantability and fitness for a particular purpose.
            </p>

            <h2 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.5rem', marginTop: '1.5rem', marginBottom: '0.75rem' }}>
              3. Limitation of Liability
            </h2>
            <p style={{ marginBottom: '1rem' }}>
              To the fullest extent permitted by law, A²Z AssistanZ, its creators, developers, affiliates, and licensors shall not be liable for any direct, indirect, incidental, special, consequential, or exemplary damages, including but not limited to, damages for loss of profits, goodwill, data, or other intangible losses, resulting from the use or inability to use the application or any information or documents derived from it.
            </p>

            <h2 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.5rem', marginTop: '1.5rem', marginBottom: '0.75rem' }}>
              4. Testimonial Disclaimer
            </h2>
            <p style={{ marginBottom: '1rem' }}>
              Please note: The testimonials presented on this application are{' '}
              <strong style={{ color: 'var(--color-primary)' }}>generated by an AI model</strong>. They are based on hypothetical scenarios and computer analysis of potential user experiences and reviews. These testimonials do{' '}
              <strong style={{ color: 'var(--color-destructive)' }}>NOT represent the actual views, experiences, or endorsements of real individuals</strong> who have used this app or service. They are provided for illustrative purposes only and should not be taken as factual representations of user satisfaction or product performance.
            </p>

            <h2 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.5rem', marginTop: '1.5rem', marginBottom: '0.75rem' }}>
              5. User Responsibility
            </h2>
            <p style={{ marginBottom: '1rem' }}>
              You, the user, are solely responsible for verifying the accuracy and applicability of any information or documents obtained from this application before using them for any purpose. Use of this application implies your understanding and acceptance of these terms.
            </p>
          </div>
        </div>

        <div style={{ flexShrink: 0, paddingTop: '1.5rem', borderTop: '1px solid var(--color-secondary)' }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', marginBottom: '1.5rem' }}>
            <label style={{ display: 'flex', alignItems: 'center', fontSize: '0.95rem' }}>
              <input
                type="checkbox"
                checked={agreements.legalAdvice}
                onChange={() => handleCheckboxChange('legalAdvice')}
                style={{ width: 'auto', height: '18px', marginRight: '0.75rem', accentColor: 'var(--color-primary)' }}
              />
              I understand that A²Z AssistanZ provides general information, not legal advice, and does not create an attorney-client relationship.
            </label>
            <label style={{ display: 'flex', alignItems: 'center', fontSize: '0.95rem' }}>
              <input
                type="checkbox"
                checked={agreements.noGuarantees}
                onChange={() => handleCheckboxChange('noGuarantees')}
                style={{ width: 'auto', height: '18px', marginRight: '0.75rem', accentColor: 'var(--color-primary)' }}
              />
              I accept that the accuracy or reliability of the output is not guaranteed and that I use the application at my own risk.
            </label>
            <label style={{ display: 'flex', alignItems: 'center', fontSize: '0.95rem' }}>
              <input
                type="checkbox"
                checked={agreements.liability}
                onChange={() => handleCheckboxChange('liability')}
                style={{ width: 'auto', height: '18px', marginRight: '0.75rem', accentColor: 'var(--color-primary)' }}
              />
              I agree to the limitation of liability for A²Z AssistanZ, its creators, and affiliates.
            </label>
            <label style={{ display: 'flex', alignItems: 'center', fontSize: '0.95rem' }}>
              <input
                type="checkbox"
                checked={agreements.testimonials}
                onChange={() => handleCheckboxChange('testimonials')}
                style={{ width: 'auto', height: '18px', marginRight: '0.75rem', accentColor: 'var(--color-primary)' }}
              />
              I understand that the testimonials are AI-generated, based on hypothetical analysis, and not from real users.
            </label>
            <label style={{ display: 'flex', alignItems: 'center', fontSize: '0.95rem' }}>
              <input
                type="checkbox"
                checked={agreements.userResponsibility}
                onChange={() => handleCheckboxChange('userResponsibility')}
                style={{ width: 'auto', height: '18px', marginRight: '0.75rem', accentColor: 'var(--color-primary)' }}
              />
              I confirm I am solely responsible for verifying information and documents before use.
            </label>
          </div>

          <button
            onClick={handleContinue}
            disabled={!allAgreed}
            className="btn btn-primary"
            style={{
              width: '100%',
              padding: '1rem',
              fontSize: '1.125rem',
              opacity: allAgreed ? 1 : 0.6,
              cursor: allAgreed ? 'pointer' : 'not-allowed',
              transform: allAgreed ? 'translateY(0)' : 'none',
              boxShadow: allAgreed ? '0 4px 15px rgba(192, 178, 131, 0.2)' : 'none',
            }}
          >
            I Understand and Agree & Continue
            {!allAgreed && <span style={{ marginLeft: '0.5rem' }}>(Please check all boxes)</span>}
          </button>
        </div>
      </div>
    </div>
  );
};

export default InitialDisclaimerSplash;
